export const insuranceConstant = {
  SEARCH_PACKAGE_FORM: '[insurance] searchPackageForm',
  PACKAGE_LIST: '[insurance] packageList',
  PACKAGE_SELECTED: '[insurance] packageSelected',
  QUOTE_SEARCH_FORM: '[insurance] quoteSearchForm',
  AUTH_AXA: '[insurance] authAXAInsurance',
  PRODUCT_SELECTED: '[insurance] productSelected',
  QUOTE_RESPONSE: '[insurance] quoteResponse',
  SUBSCRIPTION_RESPONSE: '[insurance] subscriptionResponse',
  SESSION_ID: '[insurance] sessionId',
  USER_INFO: '[insurance] userInfo',
  CARD_PAYMENT: '[insurance] cardPayment',
  INSURANCE_CURRENCY: '[insurance] currency',
  INSURANCE_PAYMENT_REQ: '[insurance] paymentRequest',
  AXA_TOKEN_EXPIRE_TIME: '[insurance] expirationTokenDate',
  HISTORY_INSURANCE_SELECTED: '[insurance] historyInsuranceSelected',
  INSURANCE_VCN_GENERATE: '[insurance] vcnGenerateReq',
  SUBSCRIBE_POLICY_DATA: '[insurance] SubscribePolicyData',
};
