export const specialPackagesConstant = {
  SESSION_ID: '[special-packages] sessionId',
  PACKAGE_SHOPPING_REQ: '[special-packages] packageShoppingReq',
  PACKAGE_SHOPPING_RES: '[special-packages] packageShoppingRes',
  SELECTED_PACKAGE: '[special-packages] selectedPackages',
  HOTEL_ROOM_LIST: '[special-packages] hotelRoomList',
  SELECTED_ROOM: '[special-packages] selectedRoom',
  SUPPLEMENT_LIST: '[special-packages] packageSupplementList',
  SELECTED_SUPPLEMENT: '[special-packages] selectedSupplement',
  TOUR_LIST: '[special-packages] packageTourList',
  SELECTED_TOUR: '[special-packages] selectedTour',
  TRANSFER_LIST: '[special-packages] packageTransferList',
  PACKAGE_OPTIONAL: '[special-packages] packageOptional',
  SUMMARY_REQ: '[special-packages] packageSummaryReq',
  SUMMARY_RESULT: '[special-packages] packageSummaryRes',
  SELECTED_TRANSFER: '[special-packages] selectedTransfer',
  USER_INFO: '[special-packages] userInfo',
  CARD_PAYMENT: '[special-packages] cardPayment',
  PACKAGES_PAYMENT_REQ: '[special-packages] tourPaymentRequest',
  PACKAGES_REFUND_TRACENUMBER: '[special-packages] refundTraceNumber',
  PACKAGE_VCN_GENERATE: '[special-packages] vcnGenerateReq'
  // AGENT_VCN: "[thingToDo] tourAgentVcn",
};
