export const providerPackagesConstant = {
  PACKAGE_HOTEL_ID: '[Package_Provider] packageHotelId',
  PACKAGE_HOTEL_NAME: '[Package_Provider] packageHotelName',
  PACKAGE_HOTEL_LIST_RES: '[Package_Provider] packageHotelListRes',
  PACKAGE_HOTEL_CREATE_REQ: '[Package_Provider] packageHotelCreateReq',
  PACKAGE_HOTEL_CREATE_RES: '[Package_Provider] packageHotelCreateRes',
  PACKAGE_HOTEL_DETAIL_RES: '[Package_Provider] packageHotelDetailRes',
  PACKAGE_HOTEL_UPDATE_RES: '[Package_Provider] packageHotelUpdateRes',
  PACKAGE_HOTEL_ROOM_LIST_RES: '[Package_Provider] packageHotelRoomListRes',
  PACKAGE_HOTEL_LIST_BY_NAME_RES: '[Package_Provider] packageHotelListByNameRes',
  PACKAGE_HOTEL_ROOM_CREATE_RES: '[Package_Provider] packageHotelRoomRes',
  PACKAGE_HOTEL_ROOM_DETAIL_RES: '[Package_Provider] packageHotelRoomDetailRes',
  PACKAGE_HOTEL_ROOM_UPDATE_RES: '[Package_Provider] packageHotelRoomUpdateRes',
  PACKAGE_INFO_LIST_RES: '[Package_Provider] packageInfoListRes',
  PACKAGE_INFO_DETAIL_RES: '[Package_Provider] packageInfoDetailRes',
  PACKAGE_INFO_CREATE_RES: '[Package_Provider] packageInfoCreateRes',
  PACKAGE_REGION_LIST_RES: '[Package_Provider] packageRegionListRes',
  PACKAGE_REGION_DETAIL_RES: '[Package_Provider] packageRegionDetailRes',
  PACKAGE_REGION_CREATE_RES: '[Package_Provider] packageRegionCreateRes',
  PACKAGE_REGION_UPDATE_RES: '[Package_Provider] packageRegionUpdateRes',
  PACKAGE_SUPPLEMENT_LIST_RES: '[Package_Provider] packageSupplementListRes',
  PACKAGE_SUPPLEMENT_CREATE_RES: '[Package_Provider] packageSupplementCreateRes',
  PACKAGE_SUPPLEMENT_DETAIL_RES: '[Package_Provider] packageSupplementDetailRes',
  PACKAGE_SUPPLEMENT_UPDATE_RES: '[Package_Provider] packageSupplementUpdateRes',
  PACKAGE_TOUR_LIST_RES: '[Package_Provider] packageTourListRes',
  PACKAGE_TOUR_CREATE_RES: '[Package_Provider] packageTourCreateRes',
  PACKAGE_TOUR_DETAIL_RES: '[Package_Provider] packageTourDetailRes',
  PACKAGE_TOUR_UPDATE_RES: '[Package_Provider] packageTourUpdateRes',
  PACKAGE_TRANSFER_LIST_RES: '[Package_Provider] packageTransferListRes',
  PACKAGE_TRANSFER_CREATE_RES: '[Package_Provider] packageTransferCreateRes',
  PACKAGE_TRANSFER_DETAIL_RES: '[Package_Provider] packageTransferDetailRes',
  PACKAGE_TRANSFER_UPDATE_RES: '[Package_Provider] packageTransferUpdateRes',
  PACKAGE_HOTEL_FACILITY_LIST_RES: '[Package_Provider] packageTransferListRes',
  PACKAGE_HOTEL_FACILITY_CREATE_RES: '[Package_Provider] packageTransferCreateRes',
  PACKAGE_HOTEL_FACILITY_DETAIL_RES: '[Package_Provider] packageTransferDetailRes',
  PACKAGE_HOTEL_FACILITY_UPDATE_RES: '[Package_Provider] packageTransferUpdateRes',

}
